# -*- coding: utf-8 -*-
"""hash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fAo2VFBcsLi884yFnj9iVttYNS1I-tgm
"""

rows = 40  
for i in range(1, rows + 1):  
    for j in range(1, rows + 1):  
        if i == rows/4 or  j == rows/4 or i == rows/2 or  j == rows/2:
            print("*", end="")
        
        else:
            print(" ", end="")
            
    print()